eureka:
  instance:
    hostname: localhost
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicle/**
          filters:
            - AuthenticationFilter
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotel/**
          filters:
            - AuthenticationFilter
        - id: guide-service
          uri: lb://guide-service
          predicates:
            - Path=/api/guide/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter
        - id: travel-service
          uri: lb://travel-service
          predicates:
            - Path=/api/travels/**,/api/packages/**
          filters:
            - AuthenticationFilter